{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Income per Month",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(order_date, 'MM') AS \"Month\",\r\n    SUM(CASE WHEN DATE_PART('year', order_date) = 2019 THEN money_spend ELSE 0 END) AS \"Revenue_2019\",\r\n    SUM(CASE WHEN DATE_PART('year', order_date) = 2020 THEN money_spend ELSE 0 END) AS \"Revenue_2020\"\r\nFROM purchase_aggregates\r\nGROUP BY \"Month\"\r\nORDER BY \"Month\";"
    }
   ]
  },
  {
   "title": "Top 10 most sold Products",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 9, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT product , SUM(quantity_ordered) as somme  FROM purchase_aggregates\r\nGROUP BY product \r\nORDER BY somme DESC  LIMIT 10;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "options": {
    "content": "# <font color=yellow>INCOME PER YEAR</font>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(money_spend) AS sum1 FROM purchase_aggregates\r\nGROUP BY EXTRACT(YEAR FROM order_date) HAVING EXTRACT(YEAR FROM order_date)=2019;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(money_spend) AS sum2 FROM purchase_aggregates\r\nGROUP BY EXTRACT(YEAR FROM order_date) HAVING EXTRACT(YEAR FROM order_date)=2020;"
    }
   ]
  },
  {
   "title": "Total items sold per Month",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    TO_CHAR(order_date, 'MM') AS \"Month\",\r\n    SUM(CASE WHEN DATE_PART('year', order_date) = 2019 THEN quantity_ordered ELSE 0 END) AS \"Total items ordered in 2019\",\r\n    SUM(CASE WHEN DATE_PART('year', order_date) = 2020 THEN quantity_ordered ELSE 0 END) AS \"Total items ordered in 2020\"\r\nFROM\r\n    purchase_aggregates\r\nGROUP BY\r\n    \"Month\"\r\nORDER BY\r\n    \"Month\";\r\n"
    }
   ]
  },
  {
   "title": "top 5 least sold products",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT product , SUM(quantity_ordered) as somme  FROM purchase_aggregates\r\nGROUP BY product \r\nORDER BY somme ASC  LIMIT 5;"
    }
   ]
  }
 ]
}